//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prexonite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prexonite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler target cannot be null..
        /// </summary>
        public static string AstNode__GetOptimizedNode_CompilerTarget_null {
            get {
                return ResourceManager.GetString("AstNode__GetOptimizedNode_CompilerTarget_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression to be optimized can not be null..
        /// </summary>
        public static string AstNode__GetOptimizedNode_Expression_null {
            get {
                return ResourceManager.GetString("AstNode__GetOptimizedNode_Expression_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When creating a compiler target, the supplied function must match the application targetted by the loader..
        /// </summary>
        public static string CompilerTarget_Cannot_create_for_foreign_function {
            get {
                return ResourceManager.GetString("CompilerTarget_Cannot_create_for_foreign_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key in source for symbol store..
        /// </summary>
        public static string ConflictUnionFallbackStore__unifySymbols_Invalid_key_in_source_for_symbol_store_ {
            get {
                return ResourceManager.GetString("ConflictUnionFallbackStore__unifySymbols_Invalid_key_in_source_for_symbol_store_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stream that is not readable cannot be used as a source..
        /// </summary>
        public static string Exception_StreamSource_CannotUseWriteOnlyStream {
            get {
                return ResourceManager.GetString("Exception.StreamSource.CannotUseWriteOnlyStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}begin compiling {0} [Path: {2} ].
        /// </summary>
        public static string Loader__begin_compiling {
            get {
                return ResourceManager.GetString("Loader__begin_compiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}end   compiling {0}.
        /// </summary>
        public static string Loader__end_compiling {
            get {
                return ResourceManager.GetString("Loader__end_compiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A MetaEntry list must not contain null references..
        /// </summary>
        public static string MetaEntry_NullReferenceInList {
            get {
                return ResourceManager.GetString("MetaEntry_NullReferenceInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use {0} like a constructor..
        /// </summary>
        public static string Parser__CannotUseExpressionAsAConstructor {
            get {
                return ResourceManager.GetString("Parser__CannotUseExpressionAsAConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert a macro instance symbol to a legacy SymbolEntry..
        /// </summary>
        public static string SymbolEntryConversion_MacroInstance_not_supported {
            get {
                return ResourceManager.GetString("SymbolEntryConversion_MacroInstance_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message symbol was not handled before conversion to a legacy SymbolEntry.
        /// </summary>
        public static string SymbolEntryConversion_MessageSymbol_cannot_be_converted_to_SymbolEntry {
            get {
                return ResourceManager.GetString("SymbolEntryConversion_MessageSymbol_cannot_be_converted_to_SymbolEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy symbol entry cannot express arbitrary dereference symbol modifiers..
        /// </summary>
        public static string SymbolEntryConversion_No_arbirtrary_dereference {
            get {
                return ResourceManager.GetString("SymbolEntryConversion_No_arbirtrary_dereference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //PRX
        ///
        ///Name sys;
        ///
        ///declare {
        ///	command:
        ///		print,println,
        ///		meta,
        ///		boxed,
        ///		concat,
        ///		map,
        ///		select,
        ///		foldl,
        ///		foldr,
        ///		dispose,
        ///		call\perform,
        ///		thunk,
        ///		asthunk,
        ///		force,
        ///		toseq,
        ///		call\member\perform,
        ///		caller,
        ///		pair,
        ///		unbind,
        ///		sort,
        ///		orderby,
        ///		LoadAssembly,
        ///		debug,
        ///		setcenter,
        ///		setleft,
        ///		setright,
        ///		all,
        ///		where,
        ///		skip,
        ///		limit,
        ///		take,
        ///		abs,
        ///		ceiling,
        ///		exp,
        ///		floor,
        ///		log,
        ///		max,
        ///		min,
        ///		pi,
        ///		round,
        ///		sin,
        ///		cos,
        ///		sqrt,
        ///		tan,
        ///		char,
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sys {
            get {
                return ResourceManager.GetString("sys", resourceCulture);
            }
        }
    }
}
