//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prexonite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prexonite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stream that is not readable cannot be used as a source..
        /// </summary>
        public static string Exception_StreamSource_CannotUseWriteOnlyStream {
            get {
                return ResourceManager.GetString("Exception.StreamSource.CannotUseWriteOnlyStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A MetaEntry list must not contain null references..
        /// </summary>
        public static string MetaEntry_NullReferenceInList {
            get {
                return ResourceManager.GetString("MetaEntry_NullReferenceInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //PRX
        ///
        ///Name sys;
        ///
        ///declare {
        ///	command:
        ///		print,println,
        ///		meta,
        ///		boxed,
        ///		concat,
        ///		map,
        ///		select,
        ///		foldl,
        ///		foldr,
        ///		dispose,
        ///		call\perform,
        ///		thunk,
        ///		asthunk,
        ///		force,
        ///		toseq,
        ///		call\member\perform,
        ///		caller,
        ///		pair,
        ///		unbind,
        ///		sort,
        ///		orderby,
        ///		LoadAssembly,
        ///		debug,
        ///		setcenter,
        ///		setleft,
        ///		setright,
        ///		all,
        ///		where,
        ///		skip,
        ///		limit,
        ///		take,
        ///		abs,
        ///		ceiling,
        ///		exp,
        ///		floor,
        ///		log,
        ///		max,
        ///		min,
        ///		pi,
        ///		round,
        ///		sin,
        ///		cos,
        ///		sqrt,
        ///		tan,
        ///		char,
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sys {
            get {
                return ResourceManager.GetString("sys", resourceCulture);
            }
        }
    }
}
