/* The following code was generated by CSFlex 1.4 on 10/04/2011 */

#line 1 "Prexonite.lex"
/*
 * Prexonite, a scripting engine (Scripting Language -> Bytecode -> Virtual Machine)
 *  Copyright (C) 2007  Christian "SealedSun" Klauser
 *  E-mail  sealedsun a.t gmail d.ot com
 *  Web     http://www.sealedsun.ch/
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  Please contact me (sealedsun a.t gmail do.t com) if you need a different license.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

//Prexonite Scanner file.

using System;
using System.Text;
using System.IO;
using Prexonite;
using Prexonite.Types;
using Prexonite.Commands;
using Prexonite.Compiler;
using Prexonite.Compiler.Ast;

partial

#line default
/**
 * This class is a scanner generated by <a href="http://www.sourceforge.net/projects/csflex/">C# Flex</a>, based on
 * <a href="http://www.jflex.de/">JFlex</a>, version 1.4
 * on 10/04/2011 from the specification file
 * <tt>Prexonite.lex</tt>
 */
class Lexer: IScanner {

  /** This character denotes the end of file */
  public const int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private const int ZZ_BUFFERSIZE = 16384;
  /**
   * This is used in 'if' statements to eliminate dead code
   * warnings for 'break;' after the end of a user action
   * block of code. The Java version does this by emitting
   * a second 'case' which is impossible to reach. Since this
   * is impossible for the compiler to deduce during semantic
   * analysis, the warning is stifled. However, C# does not
   * permit 'case' blocks to flow into each other, so the C#
   * output mode needs a different approach. In this case,
   * the entire user code is wrapped up in an 'if' statement
   * whose condition is always true. No warning is emitted
   * because the compiler doesn't strictly propagate the value
   * of 'static readonly' fields, and thus does not semantically
   * detect the fact that the 'if' will always be true.
   */
   public static readonly bool ZZ_SPURIOUS_WARNINGS_SUCK = true;

  /** lexical states */
  public const int Asm = 7;
  public const int VerbatimString = 3;
  public const int YYINITIAL = 0;
  public const int Local = 6;
  public const int SmartVerbatimString = 4;
  public const int SmartString = 2;
  public const int VerbatimBlock = 5;
  public const int String = 1;
  static Lexer()
  {
    ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);
    ZZ_ACTION = zzUnpackAction();
    ZZ_ROWMAP = zzUnpackRowMap();
    ZZ_TRANS = zzUnpackTrans();
    ZZ_ATTRIBUTE = zzUnpackAttribute();
  }


  /** 
   * Translates characters to character classes
   */
  private static readonly ushort[] ZZ_CMAP_PACKED = new ushort[] {
    9, 9, 1, 14, 1, 11, 1, 12, 1, 12, 1, 10, 14, 9, 4, 0, 1, 14, 1, 43,
    1, 15, 1, 0, 1, 16, 1, 0, 1, 40, 1, 3, 1, 36, 1, 37, 1, 18, 1, 5,
    1, 51, 1, 6, 1, 24, 1, 17, 1, 25, 9, 1, 1, 33, 1, 50, 1, 45, 1, 42,
    1, 44, 1, 49, 1, 23, 1, 30, 1, 52, 1, 2, 1, 21, 1, 4, 1, 29, 5, 7,
    1, 31, 1, 38, 1, 53, 1, 20, 2, 7, 1, 27, 1, 22, 1, 19, 1, 28, 1, 32,
    1, 7, 1, 26, 2, 7, 1, 35, 1, 8, 1, 46, 1, 39, 1, 7, 1, 0, 1, 30,
    1, 52, 1, 2, 1, 21, 1, 4, 1, 29, 5, 7, 1, 31, 1, 38, 1, 53, 1, 20,
    2, 7, 1, 27, 1, 22, 1, 19, 1, 28, 1, 32, 1, 7, 1, 26, 2, 7, 1, 34,
    1, 41, 1, 47, 1, 48, 6, 9, 1, 13, 26, 9, 2, 0, 4, 7, 4, 0, 1, 7,
    7, 0, 2, 9, 1, 0, 1, 7, 3, 0, 1, 9, 1, 7, 5, 0, 23, 7, 1, 0,
    31, 7, 1, 0, 0x0128, 7, 2, 0, 18, 7, 28, 0, 94, 7, 2, 0, 9, 7, 2, 0,
    7, 7, 14, 0, 2, 7, 14, 0, 5, 7, 9, 0, 1, 7, 17, 0, 70, 9, 26, 0,
    2, 9, 24, 0, 1, 7, 11, 0, 1, 7, 1, 0, 3, 7, 1, 0, 1, 7, 1, 0,
    20, 7, 1, 0, 44, 7, 1, 0, 8, 7, 2, 0, 26, 7, 12, 0, 130, 7, 1, 0,
    4, 9, 5, 0, 57, 7, 2, 0, 2, 7, 2, 0, 2, 7, 3, 0, 38, 7, 2, 0,
    2, 7, 55, 0, 38, 7, 2, 0, 1, 7, 7, 0, 39, 7, 9, 0, 41, 9, 1, 0,
    3, 9, 1, 0, 1, 9, 1, 0, 2, 9, 1, 0, 1, 9, 11, 0, 27, 7, 5, 0,
    3, 7, 46, 0, 26, 7, 5, 0, 11, 7, 8, 9, 13, 0, 10, 9, 6, 0, 1, 9,
    99, 7, 1, 0, 1, 7, 7, 9, 2, 0, 6, 9, 2, 7, 2, 9, 1, 0, 4, 9,
    2, 0, 10, 9, 3, 7, 19, 0, 1, 7, 1, 0, 27, 7, 83, 0, 38, 7, 0x015b, 0,
    3, 9, 1, 0, 53, 7, 2, 0, 1, 9, 1, 7, 16, 9, 2, 0, 1, 7, 4, 9,
    3, 0, 10, 7, 2, 9, 2, 0, 10, 9, 17, 0, 3, 9, 1, 0, 8, 7, 2, 0,
    2, 7, 2, 0, 22, 7, 1, 0, 7, 7, 1, 0, 1, 7, 3, 0, 4, 7, 2, 0,
    1, 9, 1, 0, 7, 9, 2, 0, 2, 9, 2, 0, 3, 9, 9, 0, 1, 9, 4, 0,
    2, 7, 1, 0, 3, 7, 2, 9, 2, 0, 10, 9, 4, 7, 4, 9, 1, 0, 1, 9,
    8, 0, 1, 9, 2, 0, 6, 7, 4, 0, 2, 7, 2, 0, 22, 7, 1, 0, 7, 7,
    1, 0, 2, 7, 1, 0, 2, 7, 1, 0, 2, 7, 2, 0, 1, 9, 1, 0, 5, 9,
    4, 0, 2, 9, 2, 0, 3, 9, 11, 0, 4, 7, 1, 0, 1, 7, 7, 0, 12, 9,
    3, 7, 12, 0, 3, 9, 1, 0, 7, 7, 1, 0, 1, 7, 1, 0, 3, 7, 1, 0,
    22, 7, 1, 0, 7, 7, 1, 0, 2, 7, 1, 0, 5, 7, 2, 0, 1, 9, 1, 7,
    8, 9, 1, 0, 3, 9, 1, 0, 3, 9, 2, 0, 1, 7, 15, 0, 1, 7, 5, 0,
    10, 9, 17, 0, 3, 9, 1, 0, 8, 7, 2, 0, 2, 7, 2, 0, 22, 7, 1, 0,
    7, 7, 1, 0, 2, 7, 2, 0, 4, 7, 2, 0, 1, 9, 1, 7, 6, 9, 3, 0,
    7, 9, 8, 0, 2, 9, 4, 0, 2, 7, 1, 0, 3, 7, 4, 0, 10, 9, 18, 0,
    2, 9, 1, 0, 6, 7, 3, 0, 3, 7, 1, 0, 4, 7, 3, 0, 2, 7, 1, 0,
    1, 7, 1, 0, 2, 7, 3, 0, 2, 7, 3, 0, 3, 7, 3, 0, 8, 7, 1, 0,
    3, 7, 4, 0, 71, 9, 8, 7, 1, 9, 3, 7, 1, 9, 23, 7, 1, 9, 10, 7,
    1, 9, 5, 7, 11, 9, 1, 0, 3, 9, 1, 0, 4, 9, 7, 0, 2, 9, 9, 0,
    2, 7, 4, 0, 10, 9, 18, 0, 2, 9, 1, 0, 8, 7, 1, 0, 3, 7, 1, 0,
    23, 7, 1, 0, 10, 7, 1, 0, 5, 7, 4, 0, 7, 9, 1, 0, 3, 9, 1, 0,
    4, 9, 7, 0, 2, 9, 7, 0, 1, 7, 1, 0, 2, 7, 4, 0, 10, 9, 18, 0,
    2, 9, 1, 0, 8, 7, 1, 0, 3, 7, 1, 0, 23, 7, 1, 0, 16, 7, 4, 0,
    6, 9, 2, 0, 3, 9, 1, 0, 4, 9, 9, 0, 1, 9, 8, 0, 2, 7, 4, 0,
    10, 9, 21, 0, 18, 7, 3, 0, 24, 7, 1, 0, 9, 7, 1, 0, 1, 7, 2, 0,
    7, 7, 58, 0, 48, 7, 1, 9, 2, 7, 7, 9, 4, 0, 8, 7, 8, 9, 1, 0,
    10, 9, 39, 0, 2, 7, 1, 0, 1, 7, 2, 0, 2, 7, 1, 0, 1, 7, 2, 0,
    1, 7, 6, 0, 4, 7, 1, 0, 7, 7, 1, 0, 3, 7, 1, 0, 1, 7, 1, 0,
    1, 7, 2, 0, 2, 7, 1, 0, 4, 7, 1, 9, 2, 7, 6, 9, 1, 0, 2, 9,
    1, 7, 2, 0, 5, 7, 1, 0, 1, 7, 1, 0, 6, 9, 2, 0, 10, 9, 2, 0,
    2, 7, 34, 0, 1, 7, 23, 0, 2, 9, 6, 0, 10, 9, 11, 0, 1, 9, 1, 0,
    1, 9, 1, 0, 1, 9, 4, 0, 2, 9, 8, 7, 1, 0, 34, 7, 6, 0, 23, 9,
    4, 7, 4, 0, 6, 9, 1, 0, 1, 9, 1, 0, 21, 9, 3, 0, 7, 9, 1, 0,
    1, 9, 70, 0, 34, 7, 1, 0, 5, 7, 1, 0, 2, 7, 37, 0, 6, 7, 74, 0,
    38, 7, 10, 0, 39, 7, 9, 0, 90, 7, 5, 0, 68, 7, 5, 0, 82, 7, 6, 0,
    7, 7, 1, 0, 63, 7, 1, 0, 1, 7, 1, 0, 4, 7, 2, 0, 7, 7, 1, 0,
    1, 7, 1, 0, 4, 7, 2, 0, 39, 7, 1, 0, 1, 7, 1, 0, 4, 7, 2, 0,
    31, 7, 1, 0, 1, 7, 1, 0, 4, 7, 2, 0, 7, 7, 1, 0, 1, 7, 1, 0,
    4, 7, 2, 0, 7, 7, 1, 0, 7, 7, 1, 0, 23, 7, 1, 0, 31, 7, 1, 0,
    1, 7, 1, 0, 4, 7, 2, 0, 7, 7, 1, 0, 39, 7, 1, 0, 19, 7, 69, 0,
    85, 7, 12, 0, 0x026c, 7, 2, 0, 8, 7, 10, 0, 26, 7, 5, 0, 75, 7, 149, 0,
    52, 7, 108, 0, 88, 7, 8, 0, 41, 7, 0x0557, 0, 156, 7, 4, 0, 90, 7, 6, 0,
    22, 7, 2, 0, 6, 7, 2, 0, 38, 7, 2, 0, 6, 7, 2, 0, 8, 7, 1, 0,
    1, 7, 1, 0, 1, 7, 1, 0, 1, 7, 1, 0, 31, 7, 2, 0, 53, 7, 1, 0,
    7, 7, 1, 0, 1, 7, 3, 0, 3, 7, 1, 0, 7, 7, 3, 0, 4, 7, 2, 0,
    6, 7, 4, 0, 13, 7, 5, 0, 3, 7, 1, 0, 7, 7, 15, 0, 4, 9, 24, 0,
    1, 12, 1, 12, 5, 9, 16, 0, 2, 7, 41, 0, 7, 9, 3, 0, 6, 9, 5, 0,
    1, 7, 10, 9, 22, 0, 12, 7, 36, 0, 13, 9, 4, 0, 1, 9, 32, 0, 1, 7,
    4, 0, 1, 7, 2, 0, 10, 7, 1, 0, 1, 7, 3, 0, 5, 7, 6, 0, 1, 7,
    1, 0, 1, 7, 1, 0, 1, 7, 1, 0, 4, 7, 1, 0, 3, 7, 1, 0, 7, 7,
    37, 0, 36, 9, 0x02dd, 0, 60, 9, 78, 0, 1, 9, 0x028b, 0, 30, 9, 0x0871, 0, 2, 7,
    1, 9, 25, 0, 15, 9, 1, 0, 5, 7, 11, 0, 84, 7, 4, 0, 2, 9, 2, 0,
    2, 7, 2, 0, 90, 7, 1, 0, 3, 7, 6, 0, 40, 7, 4, 0, 94, 7, 17, 0,
    24, 7, 200, 0, 10, 9, 0x0176, 0, 0x19b6, 7, 74, 0, 0x51a6, 7, 90, 0, 0x048d, 7, 0x0773, 0,
    0x2ba4, 7, 0x215c, 0, 0x012e, 7, 210, 0, 7, 7, 12, 0, 5, 7, 5, 0, 1, 7, 1, 0,
    10, 7, 1, 0, 13, 7, 1, 0, 5, 7, 1, 0, 1, 7, 1, 0, 2, 7, 1, 0,
    2, 7, 1, 0, 108, 7, 33, 0, 0x016b, 7, 18, 0, 64, 7, 2, 0, 54, 7, 40, 0,
    12, 7, 55, 0, 2, 7, 24, 0, 3, 7, 25, 0, 1, 7, 6, 0, 3, 7, 1, 0,
    1, 7, 1, 0, 135, 7, 2, 0, 1, 9, 4, 0, 1, 7, 11, 0, 10, 9, 7, 0,
    26, 7, 4, 0, 1, 7, 1, 0, 26, 7, 11, 0, 89, 7, 3, 0, 6, 7, 2, 0,
    6, 7, 2, 0, 6, 7, 2, 0, 3, 7, 3, 0, 2, 7, 3, 0, 2, 7, 25, 0, 0 };

  /** 
   * Translates characters to character classes
   */
  private static readonly char[] ZZ_CMAP;

  /** 
   * Translates DFA states to action switch labels.
   */
  private static readonly int [] ZZ_ACTION;

  private static readonly ushort[] ZZ_ACTION_PACKED_0 = new ushort[] {
    8, 0, 1, 1, 1, 2, 1, 3, 1, 4, 1, 5, 1, 6, 1, 7,
    1, 3, 1, 8, 1, 9, 2, 3, 1, 10, 1, 11, 1, 2, 3, 3,
    1, 12, 1, 13, 1, 14, 1, 15, 1, 16, 1, 17, 1, 18, 1, 19,
    1, 20, 1, 1, 1, 21, 1, 22, 1, 23, 1, 24, 1, 25, 1, 26,
    1, 27, 1, 28, 1, 29, 2, 30, 1, 31, 1, 32, 1, 33, 2, 34,
    1, 35, 1, 34, 1, 36, 1, 37, 1, 38, 1, 39, 1, 40, 1, 30,
    1, 41, 1, 3, 1, 10, 3, 0, 1, 42, 1, 43, 1, 44, 1, 45,
    2, 0, 1, 46, 2, 3, 1, 47, 1, 11, 1, 0, 3, 3, 1, 48,
    13, 0, 1, 49, 1, 50, 1, 51, 1, 52, 1, 53, 1, 54, 1, 55,
    1, 56, 1, 57, 1, 58, 1, 59, 1, 60, 1, 61, 1, 62, 1, 0,
    1, 63, 1, 0, 1, 64, 1, 65, 1, 66, 1, 67, 1, 68, 1, 69,
    1, 70, 1, 71, 1, 72, 1, 73, 1, 74, 1, 0, 1, 75, 1, 0,
    1, 76, 1, 77, 1, 78, 1, 79, 1, 80, 1, 81, 1, 82, 1, 83,
    1, 84, 1, 85, 1, 86, 1, 87, 1, 88, 1, 89, 1, 0, 1, 89,
    1, 90, 2, 6, 1, 0, 2, 3, 1, 2, 1, 91, 1, 3, 1, 92,
    1, 0, 1, 93, 2, 0, 1, 94, 1, 95, 1, 96, 2, 0, 1, 97,
    1, 98, 1, 99, 2, 0, 1, 100, 1, 0, 1, 101, 1, 0, 1, 102,
    1, 0, 1, 103, 1, 0, 1, 82, 1, 86, 1, 104, 1, 105, 1, 3,
    1, 106, 1, 107, 1, 108, 2, 0, 1, 109, 1, 110, 1, 111, 1, 112,
    1, 102, 1, 0, 1, 103, 1, 0, 1, 113, 1, 114, 1, 115, 1, 102,
    1, 0, 1, 103, 1, 0, 2, 102, 2, 103, 6, 0, 0 };

  private static int [] zzUnpackAction() {
    int [] result = new int[209];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(ushort[] packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.Length;
    while (i + 1 < l) {
      int count = packed[i++];
      int value = packed[i++];
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static readonly int [] ZZ_ROWMAP;

  private static readonly ushort[] ZZ_ROWMAP_PACKED_0 = new ushort[] {
    0, 0, 0, 54, 0, 108, 0, 162, 0, 216, 0, 0x010e, 0, 0x0144, 0, 0x017a,
    0, 0x01b0, 0, 0x01e6, 0, 0x021c, 0, 0x0252, 0, 0x0288, 0, 0x02be, 0, 0x01b0, 0, 0x02f4,
    0, 0x032a, 0, 0x01b0, 0, 0x0360, 0, 0x0396, 0, 0x03cc, 0, 0x0402, 0, 0x0438, 0, 0x046e,
    0, 0x04a4, 0, 0x04da, 0, 0x0510, 0, 0x01b0, 0, 0x01b0, 0, 0x0546, 0, 0x01b0, 0, 0x01b0,
    0, 0x057c, 0, 0x05b2, 0, 0x05e8, 0, 0x061e, 0, 0x0654, 0, 0x068a, 0, 0x01b0, 0, 0x01b0,
    0, 0x01b0, 0, 0x06c0, 0, 0x01b0, 0, 0x01b0, 0, 0x06f6, 0, 0x072c, 0, 0x01b0, 0, 0x01b0,
    0, 0x01b0, 0, 0x0762, 0, 0x0798, 0, 0x01b0, 0, 0x01b0, 0, 0x07ce, 0, 0x01b0, 0, 0x0804,
    0, 0x01b0, 0, 0x01b0, 0, 0x083a, 0, 0x0870, 0, 0x01b0, 0, 0x08a6, 0, 0x08dc, 0, 0x0912,
    0, 0x0948, 0, 0x097e, 0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x09b4, 0, 0x09ea, 0, 0x0a20,
    0, 0x021c, 0, 0x0a56, 0, 0x0a8c, 0, 0x01b0, 0, 0x0ac2, 0, 0x0af8, 0, 0x0b2e, 0, 0x0b64,
    0, 0x0b9a, 0, 0x01b0, 0, 0x0bd0, 0, 0x0c06, 0, 0x0c3c, 0, 0x0c72, 0, 0x0ca8, 0, 0x0cde,
    0, 0x0d14, 0, 0x0d4a, 0, 0x0d80, 0, 0x0db6, 0, 0x0dec, 0, 0x0e22, 0, 0x0e58, 0, 0x01b0,
    0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x01b0,
    0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x0e8e, 0, 0x01b0, 0, 0x0ec4,
    0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x01b0,
    0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x0efa, 0, 0x01b0, 0, 0x0f30, 0, 0x01b0, 0, 0x01b0,
    0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x0f66, 0, 0x01b0, 0, 0x01b0, 0, 0x01b0,
    0, 0x0f9c, 0, 0x01b0, 0, 0x01b0, 0, 0x0fd2, 0, 0x1008, 0, 0x103e, 0, 0x01b0, 0, 0x1074,
    0, 0x01b0, 0, 0x10aa, 0, 0x10e0, 0, 0x1116, 0, 0x0af8, 0, 0x021c, 0, 0x114c, 0, 0x021c,
    0, 0x1182, 0, 0x01b0, 0, 0x11b8, 0, 0x11ee, 0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x1224,
    0, 0x125a, 0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x1290, 0, 0x12c6, 0, 0x01b0, 0, 0x12fc,
    0, 0x01b0, 0, 0x1332, 0, 0x1368, 0, 0x139e, 0, 0x13d4, 0, 0x140a, 0, 0x01b0, 0, 0x01b0,
    0, 0x021c, 0, 0x021c, 0, 0x1440, 0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x1476, 0, 0x14ac,
    0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x01b0, 0, 0x14e2, 0, 0x1518, 0, 0x154e, 0, 0x1584,
    0, 0x021c, 0, 0x01b0, 0, 0x01b0, 0, 0x15ba, 0, 0x15f0, 0, 0x1626, 0, 0x165c, 0, 0x01b0,
    0, 0x1692, 0, 0x01b0, 0, 0x16c8, 0, 0x16fe, 0, 0x1734, 0, 0x176a, 0, 0x17a0, 0, 0x15ba,
    0, 0x1626, 0 };

  private static int [] zzUnpackRowMap() {
    int [] result = new int[209];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(ushort[] packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.Length;
    while (i + 1 < l) {
      int high = packed[i++] << 16;
      result[j++] = high | packed[i++];
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static readonly int [] ZZ_TRANS;

  private static readonly ushort[] ZZ_TRANS_PACKED_0 = new ushort[] {
    1, 9, 1, 10, 1, 11, 1, 9, 1, 11, 1, 12, 1, 13, 2, 11,
    1, 9, 5, 14, 1, 15, 1, 16, 1, 17, 1, 18, 1, 19, 1, 11,
    1, 20, 1, 11, 1, 21, 1, 22, 1, 23, 1, 11, 1, 24, 1, 11,
    1, 25, 2, 11, 1, 26, 1, 27, 1, 28, 1, 29, 1, 30, 1, 31,
    1, 11, 1, 32, 1, 33, 1, 34, 1, 35, 1, 36, 1, 37, 1, 38,
    1, 39, 1, 40, 1, 41, 1, 42, 1, 43, 1, 44, 2, 11, 8, 45,
    1, 46, 1, 45, 4, 47, 1, 45, 1, 48, 1, 49, 37, 45, 8, 50,
    1, 51, 1, 50, 4, 52, 1, 50, 1, 53, 1, 54, 37, 50, 15, 55,
    1, 56, 1, 57, 37, 55, 15, 58, 1, 59, 1, 60, 37, 58, 54, 47,
    1, 9, 1, 10, 1, 11, 1, 9, 1, 11, 1, 12, 1, 13, 2, 11,
    1, 9, 5, 14, 1, 61, 1, 16, 1, 17, 1, 18, 1, 62, 1, 11,
    1, 20, 1, 11, 1, 63, 1, 22, 1, 23, 1, 11, 1, 24, 1, 11,
    1, 25, 2, 11, 1, 26, 1, 27, 1, 28, 1, 29, 1, 30, 1, 31,
    1, 11, 1, 32, 1, 33, 1, 34, 1, 35, 1, 36, 1, 37, 1, 38,
    1, 39, 1, 40, 1, 41, 1, 42, 1, 43, 1, 44, 2, 11, 1, 9,
    1, 10, 1, 11, 1, 9, 1, 11, 1, 12, 1, 13, 2, 11, 1, 9,
    5, 14, 1, 15, 1, 16, 1, 17, 1, 18, 1, 62, 3, 11, 1, 21,
    1, 22, 1, 23, 1, 11, 1, 24, 1, 11, 1, 25, 2, 11, 1, 26,
    1, 27, 1, 28, 1, 29, 1, 30, 1, 31, 1, 11, 1, 32, 1, 33,
    1, 34, 1, 35, 1, 36, 1, 37, 1, 38, 1, 39, 1, 40, 1, 41,
    1, 42, 1, 43, 1, 44, 2, 11, 55, 0, 1, 10, 1, 0, 1, 10,
    1, 64, 19, 0, 1, 65, 1, 10, 29, 0, 4, 11, 2, 0, 3, 11,
    3, 0, 1, 11, 2, 0, 1, 11, 2, 0, 4, 11, 2, 0, 8, 11,
    1, 66, 4, 0, 1, 11, 13, 0, 2, 11, 5, 0, 1, 67, 54, 0,
    1, 68, 37, 0, 1, 69, 19, 0, 5, 14, 40, 0, 1, 11, 1, 70,
    1, 11, 1, 70, 2, 0, 2, 70, 1, 11, 3, 0, 1, 11, 2, 0,
    1, 70, 2, 0, 4, 70, 2, 0, 1, 11, 7, 70, 1, 66, 4, 0,
    1, 70, 13, 0, 2, 70, 17, 0, 1, 71, 1, 72, 36, 0, 4, 11,
    2, 0, 3, 11, 3, 0, 1, 11, 2, 0, 1, 11, 2, 0, 1, 11,
    1, 73, 2, 11, 2, 0, 2, 11, 1, 74, 5, 11, 1, 66, 4, 0,
    1, 11, 13, 0, 2, 11, 1, 0, 4, 11, 2, 0, 3, 11, 3, 0,
    1, 11, 2, 0, 1, 11, 2, 0, 1, 11, 1, 75, 2, 11, 2, 0,
    8, 11, 1, 66, 4, 0, 1, 11, 13, 0, 2, 11, 15, 0, 1, 76,
    40, 0, 1, 77, 1, 0, 1, 77, 2, 0, 2, 77, 7, 0, 1, 77,
    2, 0, 4, 77, 3, 0, 7, 77, 5, 0, 1, 77, 13, 0, 2, 77,
    1, 0, 1, 10, 1, 0, 1, 10, 1, 64, 19, 0, 1, 65, 1, 10,
    1, 78, 28, 0, 3, 11, 1, 79, 2, 0, 3, 11, 3, 0, 1, 11,
    2, 0, 1, 11, 2, 0, 4, 11, 2, 0, 8, 11, 1, 66, 4, 0,
    1, 11, 13, 0, 2, 11, 1, 0, 4, 11, 2, 0, 3, 11, 3, 0,
    1, 11, 2, 0, 1, 11, 2, 0, 4, 11, 2, 0, 5, 11, 1, 80,
    2, 11, 1, 66, 4, 0, 1, 11, 13, 0, 2, 11, 1, 0, 4, 11,
    2, 0, 3, 11, 3, 0, 1, 11, 2, 0, 1, 11, 2, 0, 4, 11,
    2, 0, 5, 11, 1, 81, 2, 11, 1, 66, 4, 0, 1, 11, 13, 0,
    2, 11, 33, 0, 1, 82, 25, 0, 1, 83, 1, 84, 10, 0, 1, 85,
    1, 86, 7, 0, 1, 87, 11, 0, 1, 88, 1, 89, 1, 90, 1, 91,
    1, 92, 1, 93, 1, 94, 1, 95, 48, 0, 1, 96, 54, 0, 1, 97,
    54, 0, 1, 98, 1, 0, 1, 99, 51, 0, 1, 100, 53, 0, 1, 101,
    1, 0, 1, 102, 51, 0, 1, 103, 2, 0, 1, 104, 57, 0, 1, 105,
    4, 0, 8, 45, 1, 0, 1, 45, 4, 0, 1, 45, 2, 0, 37, 45,
    8, 0, 1, 106, 6, 0, 1, 107, 1, 49, 2, 0, 1, 108, 5, 0,
    1, 109, 1, 110, 1, 111, 1, 112, 1, 113, 1, 114, 1, 0, 1, 115,
    7, 0, 1, 116, 11, 0, 1, 117, 1, 118, 8, 50, 1, 0, 1, 50,
    4, 0, 1, 50, 2, 0, 37, 50, 8, 0, 1, 119, 6, 0, 1, 120,
    1, 121, 2, 0, 1, 122, 5, 0, 1, 123, 1, 124, 1, 125, 1, 126,
    1, 127, 1, 128, 1, 0, 1, 129, 7, 0, 1, 130, 11, 0, 1, 131,
    1, 132, 2, 0, 1, 133, 1, 0, 1, 133, 2, 0, 2, 133, 7, 0,
    1, 133, 2, 0, 4, 133, 3, 0, 7, 133, 3, 0, 1, 134, 1, 0,
    1, 133, 13, 0, 2, 133, 15, 0, 1, 135, 53, 0, 1, 136, 40, 0,
    1, 137, 1, 0, 1, 137, 2, 0, 2, 137, 7, 0, 1, 137, 2, 0,
    4, 137, 3, 0, 7, 137, 3, 0, 1, 138, 1, 0, 1, 137, 13, 0,
    2, 137, 1, 0, 4, 11, 2, 0, 3, 11, 3, 0, 1, 11, 2, 0,
    1, 11, 2, 0, 4, 11, 2, 0, 2, 11, 1, 74, 5, 11, 1, 66,
    4, 0, 1, 11, 13, 0, 2, 11, 15, 0, 1, 139, 39, 0, 1, 140,
    3, 0, 2, 141, 18, 0, 1, 140, 29, 0, 1, 142, 23, 0, 1, 142,
    61, 0, 1, 143, 21, 0, 4, 70, 2, 0, 3, 70, 3, 0, 1, 70,
    2, 0, 1, 70, 2, 0, 4, 70, 2, 0, 8, 70, 1, 66, 4, 0,
    1, 70, 13, 0, 2, 70, 10, 71, 1, 144, 3, 145, 40, 71, 18, 72,
    1, 146, 35, 72, 1, 0, 4, 11, 2, 0, 3, 11, 3, 0, 1, 11,
    2, 0, 1, 11, 2, 0, 4, 11, 2, 0, 3, 11, 1, 147, 4, 11,
    1, 66, 4, 0, 1, 11, 13, 0, 2, 11, 1, 0, 3, 11, 1, 148,
    2, 0, 3, 11, 3, 0, 1, 11, 2, 0, 1, 11, 2, 0, 4, 11,
    2, 0, 8, 11, 1, 66, 4, 0, 1, 11, 13, 0, 2, 11, 1, 0,
    4, 77, 2, 0, 3, 77, 3, 0, 1, 77, 2, 0, 1, 77, 2, 0,
    4, 77, 2, 0, 8, 77, 5, 0, 1, 77, 13, 0, 2, 77, 1, 0,
    2, 149, 1, 0, 1, 149, 16, 0, 1, 149, 3, 0, 1, 149, 3, 0,
    2, 149, 21, 0, 1, 149, 2, 0, 4, 11, 2, 0, 3, 11, 3, 0,
    1, 11, 2, 0, 1, 11, 2, 0, 4, 11, 2, 0, 4, 11, 1, 150,
    3, 11, 1, 66, 4, 0, 1, 11, 13, 0, 2, 11, 1, 0, 4, 11,
    2, 0, 3, 11, 3, 0, 1, 11, 2, 0, 1, 11, 2, 0, 4, 11,
    2, 0, 6, 11, 1, 151, 1, 11, 1, 66, 4, 0, 1, 11, 13, 0,
    2, 11, 1, 0, 4, 11, 2, 0, 3, 11, 3, 0, 1, 11, 2, 0,
    1, 11, 2, 0, 4, 11, 2, 0, 2, 11, 1, 152, 5, 11, 1, 66,
    4, 0, 1, 11, 13, 0, 2, 11, 5, 0, 1, 153, 31, 0, 1, 154,
    22, 0, 1, 155, 17, 0, 1, 156, 12, 0, 1, 157, 53, 0, 1, 158,
    53, 0, 1, 159, 36, 0, 1, 160, 53, 0, 1, 161, 70, 0, 1, 162,
    53, 0, 1, 163, 53, 0, 1, 164, 58, 0, 1, 165, 53, 0, 1, 166,
    48, 0, 1, 167, 4, 0, 1, 168, 48, 0, 1, 169, 4, 0, 1, 170,
    12, 0, 2, 171, 1, 0, 1, 171, 16, 0, 1, 171, 3, 0, 1, 171,
    3, 0, 2, 171, 21, 0, 1, 171, 2, 0, 2, 172, 1, 0, 1, 172,
    16, 0, 1, 172, 3, 0, 1, 172, 3, 0, 2, 172, 21, 0, 1, 172,
    2, 0, 2, 173, 1, 0, 1, 173, 16, 0, 1, 173, 3, 0, 1, 173,
    3, 0, 2, 173, 21, 0, 1, 173, 2, 0, 2, 174, 1, 0, 1, 174,
    16, 0, 1, 174, 3, 0, 1, 174, 3, 0, 2, 174, 21, 0, 1, 174,
    2, 0, 4, 133, 2, 0, 3, 133, 3, 0, 1, 133, 2, 0, 1, 133,
    2, 0, 4, 133, 2, 0, 8, 133, 5, 0, 1, 133, 1, 0, 1, 175,
    11, 0, 2, 133, 1, 0, 4, 137, 2, 0, 3, 137, 3, 0, 1, 137,
    2, 0, 1, 137, 2, 0, 4, 137, 2, 0, 8, 137, 5, 0, 1, 137,
    1, 0, 1, 176, 11, 0, 2, 137, 1, 0, 1, 140, 1, 0, 1, 140,
    21, 0, 1, 140, 29, 0, 1, 140, 23, 0, 1, 140, 29, 0, 1, 142,
    1, 0, 1, 142, 1, 64, 20, 0, 1, 142, 39, 0, 1, 145, 42, 0,
    17, 72, 1, 145, 1, 146, 35, 72, 1, 0, 3, 11, 1, 177, 2, 0,
    3, 11, 3, 0, 1, 11, 2, 0, 1, 11, 2, 0, 4, 11, 2, 0,
    8, 11, 1, 66, 4, 0, 1, 11, 13, 0, 2, 11, 1, 0, 4, 11,
    2, 0, 3, 11, 3, 0, 1, 11, 2, 0, 1, 11, 2, 0, 3, 11,
    1, 178, 2, 0, 8, 11, 1, 66, 4, 0, 1, 11, 13, 0, 2, 11,
    1, 0, 4, 11, 2, 0, 3, 11, 3, 0, 1, 11, 2, 0, 1, 11,
    2, 0, 3, 11, 1, 179, 2, 0, 8, 11, 1, 66, 4, 0, 1, 11,
    13, 0, 2, 11, 37, 0, 1, 180, 53, 0, 1, 181, 53, 0, 1, 182,
    43, 0, 1, 183, 47, 0, 1, 184, 69, 0, 1, 185, 53, 0, 1, 186,
    53, 0, 1, 187, 53, 0, 1, 188, 17, 0, 2, 189, 1, 0, 1, 189,
    16, 0, 1, 189, 3, 0, 1, 189, 3, 0, 2, 189, 21, 0, 1, 189,
    2, 0, 2, 190, 1, 0, 1, 190, 16, 0, 1, 190, 3, 0, 1, 190,
    3, 0, 2, 190, 21, 0, 1, 190, 2, 0, 2, 191, 1, 0, 1, 191,
    16, 0, 1, 191, 3, 0, 1, 191, 3, 0, 2, 191, 21, 0, 1, 191,
    2, 0, 2, 192, 1, 0, 1, 192, 16, 0, 1, 192, 3, 0, 1, 192,
    3, 0, 2, 192, 21, 0, 1, 192, 2, 0, 3, 11, 1, 193, 2, 0,
    3, 11, 3, 0, 1, 11, 2, 0, 1, 11, 2, 0, 4, 11, 2, 0,
    8, 11, 1, 66, 4, 0, 1, 11, 13, 0, 2, 11, 37, 0, 1, 194,
    53, 0, 1, 195, 17, 0, 2, 196, 1, 0, 1, 196, 16, 0, 1, 196,
    3, 0, 1, 196, 3, 0, 2, 196, 21, 0, 1, 196, 2, 0, 2, 197,
    1, 0, 1, 197, 16, 0, 1, 197, 3, 0, 1, 197, 3, 0, 2, 197,
    21, 0, 1, 197, 2, 0, 2, 198, 1, 0, 1, 198, 16, 0, 1, 198,
    3, 0, 1, 198, 3, 0, 2, 198, 21, 0, 1, 198, 2, 0, 2, 199,
    1, 0, 1, 199, 16, 0, 1, 199, 3, 0, 1, 199, 3, 0, 2, 199,
    21, 0, 1, 199, 2, 0, 2, 200, 1, 0, 1, 200, 16, 0, 1, 200,
    3, 0, 1, 200, 3, 0, 2, 200, 21, 0, 1, 200, 2, 0, 2, 201,
    1, 0, 1, 201, 16, 0, 1, 201, 3, 0, 1, 201, 3, 0, 2, 201,
    21, 0, 1, 201, 2, 0, 2, 202, 1, 0, 1, 202, 16, 0, 1, 202,
    3, 0, 1, 202, 3, 0, 2, 202, 21, 0, 1, 202, 2, 0, 2, 203,
    1, 0, 1, 203, 16, 0, 1, 203, 3, 0, 1, 203, 3, 0, 2, 203,
    21, 0, 1, 203, 2, 0, 2, 204, 1, 0, 1, 204, 16, 0, 1, 204,
    3, 0, 1, 204, 3, 0, 2, 204, 21, 0, 1, 204, 2, 0, 2, 205,
    1, 0, 1, 205, 16, 0, 1, 205, 3, 0, 1, 205, 3, 0, 2, 205,
    21, 0, 1, 205, 2, 0, 2, 206, 1, 0, 1, 206, 16, 0, 1, 206,
    3, 0, 1, 206, 3, 0, 2, 206, 21, 0, 1, 206, 2, 0, 2, 207,
    1, 0, 1, 207, 16, 0, 1, 207, 3, 0, 1, 207, 3, 0, 2, 207,
    21, 0, 1, 207, 2, 0, 2, 208, 1, 0, 1, 208, 16, 0, 1, 208,
    3, 0, 1, 208, 3, 0, 2, 208, 21, 0, 1, 208, 2, 0, 2, 209,
    1, 0, 1, 209, 16, 0, 1, 209, 3, 0, 1, 209, 3, 0, 2, 209,
    21, 0, 1, 209, 1, 0, 0 };

  private static int [] zzUnpackTrans() {
    int [] result = new int[6102];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(ushort[] packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.Length;
    while (i + 1 < l) {
      int count = packed[i++];
      int value = packed[i++];
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private const int ZZ_UNKNOWN_ERROR = 0;
  private const int ZZ_NO_MATCH = 1;
  private const int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static readonly String[] ZZ_ERROR_MSG = new string[] {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static readonly int [] ZZ_ATTRIBUTE;

  private static readonly ushort[] ZZ_ATTRIBUTE_PACKED_0 = new ushort[] {
    8, 0, 1, 9, 5, 1, 1, 9, 2, 1, 1, 9, 9, 1, 2, 9,
    1, 1, 2, 9, 6, 1, 3, 9, 1, 1, 2, 9, 2, 1, 3, 9,
    2, 1, 2, 9, 1, 1, 1, 9, 1, 1, 2, 9, 2, 1, 1, 9,
    2, 1, 3, 0, 3, 9, 1, 1, 2, 0, 3, 1, 1, 9, 1, 1,
    1, 0, 3, 1, 1, 9, 13, 0, 14, 9, 1, 0, 1, 9, 1, 0,
    11, 9, 1, 0, 1, 9, 1, 0, 6, 9, 1, 1, 3, 9, 1, 1,
    2, 9, 1, 1, 1, 0, 1, 1, 1, 9, 1, 1, 1, 9, 1, 0,
    6, 1, 1, 0, 1, 9, 2, 0, 3, 9, 2, 0, 3, 9, 2, 0,
    1, 9, 1, 0, 1, 9, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
    2, 9, 3, 1, 3, 9, 2, 0, 4, 9, 1, 1, 1, 0, 1, 1,
    1, 0, 1, 1, 2, 9, 1, 1, 1, 0, 1, 1, 1, 0, 1, 9,
    1, 1, 1, 9, 1, 1, 6, 0, 0 };

  private static int [] zzUnpackAttribute() {
    int [] result = new int[209];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(ushort[] packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.Length;
    while (i + 1 < l) {
      int count = packed[i++];
      int value = packed[i++];
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private System.IO.TextReader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char[] zzBuffer = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private bool zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private bool zzAtEOF;


  /** the stack of open (nested) input streams to read from */
  private System.Collections.Stack zzStreams = new System.Collections.Stack();

  /**
   * inner class used to store info for nested
   * input streams
   */
  private sealed class ZzFlexStreamInfo {
    public System.IO.TextReader zzReader;
    public int zzEndRead;
    public int zzStartRead;
    public int zzCurrentPos;
    public int zzMarkedPos;
    public int zzPushbackPos;
    public int yyline;
    public int yycolumn;
    public char [] zzBuffer;
    public bool zzAtEOF;

    /** sets all values stored in this class */
    public ZzFlexStreamInfo(System.IO.TextReader zzReader, int zzEndRead, int zzStartRead,
                  int zzCurrentPos, int zzMarkedPos, int zzPushbackPos,
                  char [] zzBuffer, bool zzAtEOF, int yyline, int yycolumn) {
      this.zzReader      = zzReader;
      this.zzEndRead     = zzEndRead;
      this.zzStartRead   = zzStartRead;
      this.zzCurrentPos  = zzCurrentPos;
      this.zzMarkedPos   = zzMarkedPos;
      this.zzPushbackPos = zzPushbackPos;
      this.zzBuffer      = zzBuffer;
      this.zzAtEOF       = zzAtEOF;
      this.yyline         = yyline;
      this.yycolumn       = yycolumn;
    }
  }


  /**
   * Creates a new scanner
   * There is also a System.IO.Stream version of this constructor.
   *
   * @param   in  the System.IO.TextReader to read input from.
   */
  internal Lexer(TextReader @in) {
    this.zzReader = @in;
  }

  /**
   * Creates a new scanner.
   * There is also TextReader version of this constructor.
   *
   * @param   in  the System.IO.Stream to read input from.
   */
  internal Lexer(Stream @in) : this(new StreamReader(@in))
  {
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(ushort[] packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1600) {
      int  count = packed[i++];
      char value = (char)packed[i++];
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   System.IO.IOException  if any I/O-Error occurs
   */
  private bool zzRefill() {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      Array.Copy(zzBuffer, zzStartRead,
                 zzBuffer, 0,
                 zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.Length) {
      /* if not: blow it up */
      char[] newBuffer = new char[zzCurrentPos*2];
      Array.Copy(zzBuffer, 0, newBuffer, 0, zzBuffer.Length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.Read(zzBuffer, zzEndRead,
                                            zzBuffer.Length-zzEndRead);

    if (numRead <= 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public void yyclose() {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.Close();
  }


  /**
   * Stores the current input stream on a stack, and
   * reads from a new stream. Lexical state, line,
   * char, and column counting remain untouched.
   *
   * The current input stream can be restored with
   * yypopstream (usually in an <<EOF>> action).
   *
   * @param reader the new input stream to read from
   *
   * @see #yypopStream()
   */
  public void yypushStream(TextReader reader) {
    zzStreams.Push(
      new ZzFlexStreamInfo(zzReader, zzEndRead, zzStartRead, zzCurrentPos,
                        zzMarkedPos, zzPushbackPos, zzBuffer, zzAtEOF,
                        yyline, yycolumn)
    );
    zzAtEOF  = false;
    zzBuffer = new char[ZZ_BUFFERSIZE];
    zzReader = reader;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yycolumn = 0;
  }
    

  /**
   * Closes the current input stream and continues to
   * read from the one on top of the stream stack. 
   *
   * @throws System.InvalidOperationException
   *         if there is no further stream to read from.
   *
   * @throws System.IO.IOException
   *         if there was an error in closing the stream.
   *
   * @see #yypushStream(TextReader)
   */
  public void yypopStream() {
    zzReader.Close();
    ZzFlexStreamInfo s = (ZzFlexStreamInfo) zzStreams.Pop();
    zzBuffer      = s.zzBuffer;
    zzReader      = s.zzReader;
    zzEndRead     = s.zzEndRead;
    zzStartRead   = s.zzStartRead;
    zzCurrentPos  = s.zzCurrentPos;
    zzMarkedPos   = s.zzMarkedPos ;
    zzPushbackPos = s.zzPushbackPos;
    zzAtEOF       = s.zzAtEOF;
    yyline         = s.yyline;
    yycolumn       = s.yycolumn;
  }


  /**
   * Returns true iff there are still streams left 
   * to read from on the stream stack.
   */
  public bool yymoreStreams() {
    return zzStreams.Count != 0;
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   *
   * @see #yypushStream(System.IO.TextReader)
   * @see #yypopStream()
   */
  public void yyreset(System.IO.TextReader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex/CSFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (IndexOutOfRangeException) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Exception(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   System.IO.IOException  if any I/O-Error occurs
   */
  public Token Scan() {
    int zzInput = 0;
    int zzAction;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      // cached fields:
      int zzCurrentPosL;
      int zzMarkedPosL = zzMarkedPos;
      int zzEndReadL = zzEndRead;
      char [] zzBufferL = zzBuffer;
      char [] zzCMapL = ZZ_CMAP;

      yychar+= zzMarkedPosL-zzStartRead;

      bool zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
          break;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        bool zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          bool eof = zzRefill();
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


        while (true) {
          goto zzForAction_skip;
        zzForAction: break;
        zzForAction_skip:
          if (!ZZ_SPURIOUS_WARNINGS_SUCK) goto zzForAction;
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            goto zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            bool eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
            goto zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) goto zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) goto zzForAction;
          }

        }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 49: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 145 "Prexonite.lex"
              return tok(Parser._and); 
#line default
          }
          break;
        case 92: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 102 "Prexonite.lex"
              return tok(Parser._var); 
#line default
          }
          break;
        case 32: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 200 "Prexonite.lex"
                          buffer.Append("$"); 
#line default
          }
          break;
        case 57: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 174 "Prexonite.lex"
           return tok(Parser._appendleft); 
#line default
          }
          break;
        case 29: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 184 "Prexonite.lex"
                           buffer.Append(yytext()); 
#line default
          }
          break;
        case 56: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 153 "Prexonite.lex"
              return tok(Parser._le); 
#line default
          }
          break;
        case 43: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 156 "Prexonite.lex"
              return tok(Parser._dec); 
#line default
          }
          break;
        case 17: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 142 "Prexonite.lex"
              return tok(Parser._pow); 
#line default
          }
          break;
        case 40: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 264 "Prexonite.lex"
                  PopState();
                  ret(tok(Parser._string, buffer.ToString()));
                  buffer.Length = 0;
                
#line default
          }
          break;
        case 37: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 253 "Prexonite.lex"
                  PopState();
                  ret(tok(Parser._string, buffer.ToString()));
                  buffer.Length = 0;
                
#line default
          }
          break;
        case 35: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 204 "Prexonite.lex"
                  PopState();
                  ret(tok(Parser._string, buffer.ToString()));
                  buffer.Length = 0;
                
#line default
          }
          break;
        case 31: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 180 "Prexonite.lex"
                  PopState();
                  ret(tok(Parser._string, buffer.ToString()));
                  buffer.Length = 0;
                
#line default
          }
          break;
        case 10: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 172 "Prexonite.lex"
              return tok(Parser._at); 
#line default
          }
          break;
        case 109: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 125 "Prexonite.lex"
              return tok(Parser._id,OperatorNames.Prexonite.Equality); 
#line default
          }
          break;
        case 102: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 198 "Prexonite.lex"
                                                                                                          buffer.Append(unescape_char(yytext())); 
#line default
          }
          break;
        case 93: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 116 "Prexonite.lex"
             return tok(Parser._id,OperatorNames.Prexonite.Addition); 
#line default
          }
          break;
        case 65: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 189 "Prexonite.lex"
                  buffer.Append("\a"); 
#line default
          }
          break;
        case 21: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 151 "Prexonite.lex"
              return tok(Parser._gt); 
#line default
          }
          break;
        case 36: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 257 "Prexonite.lex"
                                  buffer.Append(yytext()); 
#line default
          }
          break;
        case 5: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 139 "Prexonite.lex"
              return tok(Parser._minus); 
#line default
          }
          break;
        case 80: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 214 "Prexonite.lex"
                  buffer.Append("\b"); 
#line default
          }
          break;
        case 76: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 215 "Prexonite.lex"
                  buffer.Append("\f"); 
#line default
          }
          break;
        case 6: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 93 "Prexonite.lex"
                  /* Comment/Whitespace: ignore */ 
#line default
          }
          break;
        case 110: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 126 "Prexonite.lex"
              return tok(Parser._id,OperatorNames.Prexonite.Inequality); 
#line default
          }
          break;
        case 68: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 190 "Prexonite.lex"
                  buffer.Append("\b"); 
#line default
          }
          break;
        case 26: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 160 "Prexonite.lex"
              return tok(Parser._question); 
#line default
          }
          break;
        case 16: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 135 "Prexonite.lex"
              return tok(Parser._rpar); 
#line default
          }
          break;
        case 85: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 269 "Prexonite.lex"
                  buffer.Append("\""); 
#line default
          }
          break;
        case 52: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 162 "Prexonite.lex"
              return tok(Parser._implementation); 
#line default
          }
          break;
        case 25: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 157 "Prexonite.lex"
              return tok(Parser._tilde); 
#line default
          }
          break;
        case 50: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 146 "Prexonite.lex"
              return tok(Parser._or); 
#line default
          }
          break;
        case 42: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 155 "Prexonite.lex"
              return tok(Parser._inc); 
#line default
          }
          break;
        case 30: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 299 "Prexonite.lex"
                  throw new PrexoniteException(System.String.Format("Invalid character \"{0}\" detected on line {1} in {2}.", yytext(), yyline, File)); 
#line default
          }
          break;
        case 106: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 132 "Prexonite.lex"
              return tok(Parser._id,OperatorNames.Prexonite.Increment); 
#line default
          }
          break;
        case 74: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 212 "Prexonite.lex"
                  buffer.Append("\0"); 
#line default
          }
          break;
        case 84: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 258 "Prexonite.lex"
                  buffer.Append("\""); 
#line default
          }
          break;
        case 20: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 143 "Prexonite.lex"
              return tok(Parser._assign); 
#line default
          }
          break;
        case 18: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 148 "Prexonite.lex"
              return tok(Parser._bitAnd); 
#line default
          }
          break;
        case 33: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 208 "Prexonite.lex"
                           buffer.Append(yytext()); 
#line default
          }
          break;
        case 79: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 211 "Prexonite.lex"
                  /* nothing to do  */ 
#line default
          }
          break;
        case 3: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 111 "Prexonite.lex"
                    return tok(checkKeyword(yytext()), yytext()); 
#line default
          }
          break;
        case 11: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 166 "Prexonite.lex"
                              Token dot = tok(Parser._dot); 
                              string memberId = yytext(); 
                              if(memberId.Length > 1)
                                return multiple(dot,tok(Parser._id,memberId.Substring(memberId.StartsWith(".$") ? 2 : 1)));
                              else 
                                return dot; 
#line default
          }
          break;
        case 114: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 124 "Prexonite.lex"
                            return tok(Parser._id,OperatorNames.Prexonite.ExclusiveOr); 
#line default
          }
          break;
        case 71: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 210 "Prexonite.lex"
                  buffer.Append("\""); 
#line default
          }
          break;
        case 88: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 86 "Prexonite.lex"
                  buffer.Length = 0; PushState(SmartVerbatimString); 
#line default
          }
          break;
        case 75: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 217 "Prexonite.lex"
                  buffer.Append("\r"); 
#line default
          }
          break;
        case 45: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 109 "Prexonite.lex"
                           return tok(Parser._id, yytext().Substring(1)); 
#line default
          }
          break;
        case 72: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 223 "Prexonite.lex"
                  buffer.Append("$"); 
#line default
          }
          break;
        case 8: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 141 "Prexonite.lex"
              return tok(Parser._div); 
#line default
          }
          break;
        case 81: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 216 "Prexonite.lex"
                  buffer.Append("\n"); 
#line default
          }
          break;
        case 7: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 79 "Prexonite.lex"
                    buffer.Length = 0; PushState(String); 
#line default
          }
          break;
        case 60: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 186 "Prexonite.lex"
                  buffer.Append("\""); 
#line default
          }
          break;
        case 77: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 213 "Prexonite.lex"
                  buffer.Append("\a"); 
#line default
          }
          break;
        case 66: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 194 "Prexonite.lex"
                  buffer.Append("\v"); 
#line default
          }
          break;
        case 67: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 187 "Prexonite.lex"
                  /* nothing to do  */ 
#line default
          }
          break;
        case 58: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 159 "Prexonite.lex"
           return tok(Parser._coalescence); 
#line default
          }
          break;
        case 23: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 136 "Prexonite.lex"
              return tok(Parser._rbrack); 
#line default
          }
          break;
        case 34: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 249 "Prexonite.lex"
                  throw new PrexoniteException("Invalid smart string character '" + yytext() + "' (ASCII " + ((int)yytext()[0]) + ") in input on line " + yyline + "."); 
#line default
          }
          break;
        case 47: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 80 "Prexonite.lex"
                    buffer.Length = 0; PushState(VerbatimString); 
#line default
          }
          break;
        case 89: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 95 "Prexonite.lex"
                                                            return tok(Parser._real, yytext()); 
#line default
          }
          break;
        case 103: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 222 "Prexonite.lex"
                                                                                                          buffer.Append(unescape_char(yytext())); 
#line default
          }
          break;
        case 48: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 158 "Prexonite.lex"
              return tok(Parser._doublecolon); 
#line default
          }
          break;
        case 91: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 103 "Prexonite.lex"
              return tok(Parser._ref); 
#line default
          }
          break;
        case 96: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 118 "Prexonite.lex"
             return tok(Parser._id,OperatorNames.Prexonite.Multiplication); 
#line default
          }
          break;
        case 46: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 70 "Prexonite.lex"
                  return tok(Parser._to); 
#line default
          }
          break;
        case 9: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 140 "Prexonite.lex"
              return tok(Parser._times); 
#line default
          }
          break;
        case 22: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 154 "Prexonite.lex"
              return tok(Parser._lt); 
#line default
          }
          break;
        case 44: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 161 "Prexonite.lex"
              return tok(Parser._pointer); 
#line default
          }
          break;
        case 39: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 268 "Prexonite.lex"
                                  buffer.Append(yytext()); 
#line default
          }
          break;
        case 105: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 74 "Prexonite.lex"
              return tok(Parser._does); 
#line default
          }
          break;
        case 70: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 209 "Prexonite.lex"
                  buffer.Append("\\"); 
#line default
          }
          break;
        case 86: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 271 "Prexonite.lex"
                        string clipped;
                        string id = _pruneSmartStringIdentifier(yytext(), out clipped);
                        string fragment = buffer.ToString();
                        buffer.Length = 0;
                        return multiple(
                            tok(Parser._string, fragment),
                            tok(Parser._plus),
                            tok(Parser._id, id),
                            clipped != null ? tok(Parser._plus) : null,
                            clipped != null ? tok(Parser._string, clipped) : null,
                            tok(Parser._plus)
                        );
                     
#line default
          }
          break;
        case 100: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 127 "Prexonite.lex"
             return tok(Parser._id,OperatorNames.Prexonite.GreaterThan); 
#line default
          }
          break;
        case 4: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 138 "Prexonite.lex"
              return tok(Parser._plus); 
#line default
          }
          break;
        case 28: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 165 "Prexonite.lex"
              return tok(Parser._comma); 
#line default
          }
          break;
        case 98: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 122 "Prexonite.lex"
             return tok(Parser._id,OperatorNames.Prexonite.BitwiseAnd); 
#line default
          }
          break;
        case 78: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 218 "Prexonite.lex"
                  buffer.Append("\v"); 
#line default
          }
          break;
        case 24: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 137 "Prexonite.lex"
              return tok(Parser._rbrace); 
#line default
          }
          break;
        case 13: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 114 "Prexonite.lex"
              return tok(Parser._lbrace); 
#line default
          }
          break;
        case 73: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 219 "Prexonite.lex"
                  buffer.Append("\t"); 
#line default
          }
          break;
        case 62: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 188 "Prexonite.lex"
                  buffer.Append("\0"); 
#line default
          }
          break;
        case 41: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 85 "Prexonite.lex"
                  buffer.Length = 0; PushState(SmartString); 
#line default
          }
          break;
        case 90: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 105 "Prexonite.lex"
                         string ns = yytext();
                         return tok(Parser._ns, ns.Substring(0, ns.Length-2)); 
#line default
          }
          break;
        case 107: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 133 "Prexonite.lex"
              return tok(Parser._id,OperatorNames.Prexonite.Decrement); 
#line default
          }
          break;
        case 51: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 149 "Prexonite.lex"
              return tok(Parser._eq); 
#line default
          }
          break;
        case 15: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 134 "Prexonite.lex"
              return tok(Parser._lpar); 
#line default
          }
          break;
        case 1: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 176 "Prexonite.lex"
              Console.WriteLine("Rogue Character: \"{0}\"", yytext()); 
#line default
          }
          break;
        case 55: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 173 "Prexonite.lex"
           return tok(Parser._appendright); 
#line default
          }
          break;
        case 64: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 191 "Prexonite.lex"
                  buffer.Append("\f"); 
#line default
          }
          break;
        case 101: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 129 "Prexonite.lex"
             return tok(Parser._id,OperatorNames.Prexonite.LessThan); 
#line default
          }
          break;
        case 54: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 152 "Prexonite.lex"
              return tok(Parser._ge); 
#line default
          }
          break;
        case 38: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 259 "Prexonite.lex"
                  buffer.Append("$"); 
#line default
          }
          break;
        case 87: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 284 "Prexonite.lex"
                        string fragment = buffer.ToString(); 
                        buffer.Length = 0;
                        PushState(Local);
                        return multiple(
                            tok(Parser._string, fragment),
                            tok(Parser._plus),
                            tok(Parser._LPopExpr),
                            tok(Parser._lpar)
                            //2nd plus is injected by the parser
                        );
                     
#line default
          }
          break;
        case 95: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 119 "Prexonite.lex"
             return tok(Parser._id,OperatorNames.Prexonite.Division); 
#line default
          }
          break;
        case 115: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 120 "Prexonite.lex"
                            return tok(Parser._id,OperatorNames.Prexonite.Modulus); 
#line default
          }
          break;
        case 12: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 163 "Prexonite.lex"
              return tok(Parser._colon); 
#line default
          }
          break;
        case 113: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 101 "Prexonite.lex"
               return tok(Parser._false); 
#line default
          }
          break;
        case 14: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 115 "Prexonite.lex"
              return tok(Parser._lbrack); 
#line default
          }
          break;
        case 53: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 150 "Prexonite.lex"
              return tok(Parser._ne); 
#line default
          }
          break;
        case 82: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 225 "Prexonite.lex"
                        string clipped;
                        string id = _pruneSmartStringIdentifier(yytext(), out clipped);
                        string fragment = buffer.ToString();
                        buffer.Length = 0;
                        return multiple(
                            tok(Parser._string, fragment),
                            tok(Parser._plus),
                            tok(Parser._id, id),
                            clipped != null ? tok(Parser._plus) : null,
                            clipped != null ? tok(Parser._string, clipped) : null,
                            tok(Parser._plus)
                        );
                     
#line default
          }
          break;
        case 112: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 130 "Prexonite.lex"
              return tok(Parser._id,OperatorNames.Prexonite.LessThanOrEqual); 
#line default
          }
          break;
        case 59: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 185 "Prexonite.lex"
                  buffer.Append("\\"); 
#line default
          }
          break;
        case 27: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 164 "Prexonite.lex"
              return tok(Parser._semicolon); 
#line default
          }
          break;
        case 104: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 100 "Prexonite.lex"
              return tok(Parser._true); 
#line default
          }
          break;
        case 97: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 121 "Prexonite.lex"
             return tok(Parser._id,OperatorNames.Prexonite.Power); 
#line default
          }
          break;
        case 63: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 193 "Prexonite.lex"
                  buffer.Append("\r"); 
#line default
          }
          break;
        case 83: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 238 "Prexonite.lex"
                        string fragment = buffer.ToString(); 
                        buffer.Length = 0;
                        PushState(Local);
                        return multiple(
                            tok(Parser._string, fragment),
                            tok(Parser._plus),
                            tok(Parser._LPopExpr),
                            tok(Parser._lpar)
                            //2nd plus is injected by the parser
                        );
                     
#line default
          }
          break;
        case 61: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 195 "Prexonite.lex"
                  buffer.Append("\t"); 
#line default
          }
          break;
        case 2: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 98 "Prexonite.lex"
                                  return tok(Parser._integer, yytext()); 
#line default
          }
          break;
        case 99: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 123 "Prexonite.lex"
             return tok(Parser._id,OperatorNames.Prexonite.BitwiseOr); 
#line default
          }
          break;
        case 19: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 147 "Prexonite.lex"
              return tok(Parser._bitOr); 
#line default
          }
          break;
        case 108: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 131 "Prexonite.lex"
              return tok(Parser._id,OperatorNames.Prexonite.UnaryNegation); 
#line default
          }
          break;
        case 111: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 128 "Prexonite.lex"
              return tok(Parser._id,OperatorNames.Prexonite.GreaterThanOrEqual); 
#line default
          }
          break;
        case 69: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 192 "Prexonite.lex"
                  buffer.Append("\n"); 
#line default
          }
          break;
        case 94: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 117 "Prexonite.lex"
             return tok(Parser._id,OperatorNames.Prexonite.Subtraction); 
#line default
          }
          break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              if (ZZ_SPURIOUS_WARNINGS_SUCK)
              {     return tok(Parser._EOF);
 }
              break;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
          break;
      }
    }
  }


}
