name: PxCoco CI

on: 
  push:
    branches:
      - main
      - master
    tags-ignore:  
      - '**'
    paths:
      - PxCoco/**
      - .github/workflows/PxCocoCi.yml
  pull_request: 
    paths:
      - PxCoco/**

jobs:
  build:
    name: Build PxCoco (CI)
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 6 SDK
        uses: actions/setup-dotnet@v1.7.2
        env:
          NUGET_AUTH_TOKEN: '${{secrets.GITHUB_TOKEN}}'
        with:
          dotnet-version: '8.0.x'
          source-url: 'https://nuget.pkg.github.com/chklauser/index.json'
      - name: Setup .NET 5 SDK (for T4)
        uses: actions/setup-dotnet@v1.7.2
        env:
          NUGET_AUTH_TOKEN: '${{secrets.GITHUB_TOKEN}}'
        with:
          dotnet-version: '5.0.x'
          source-url: 'https://nuget.pkg.github.com/chklauser/index.json'
      - name: Install dependencies (Win)
        run: dotnet restore PxCoco/PxCoco.csproj
      - name: Build (Win)
        run: dotnet build --configuration Release --no-restore PxCoco/PxCoco.csproj
      - name: Pack (Win)
        run: dotnet pack --no-restore --no-build --configuration Release PxCoco/PxCoco.csproj

